// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgressiveSinglePageWebApp.DataAccess;

namespace ProgressiveSinglePageWebApp.DataAccess.Migrations
{
    [DbContext(typeof(PWADbContext))]
    [Migration("20190822031755_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ProgressiveSinglePageWebApp.DataAccess.Models.SampleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChangedBy");

                    b.Property<DateTimeOffset>("ChangedOn");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<int>("MyIntProperty");

                    b.Property<string>("Observations");

                    b.Property<long>("VersionNumber");

                    b.HasKey("Id");

                    b.ToTable("SampleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
