// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgressiveSinglePageWebApp.DataAccess;

namespace ProgressiveSinglePageWebApp.DataAccess.Migrations
{
    [DbContext(typeof(PWADbContext))]
    partial class PWADbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ProgressiveSinglePageWebApp.DataAccess.Models.SampleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChangedBy");

                    b.Property<DateTimeOffset>("ChangedOn");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Observations");

                    b.Property<double>("Temperature");

                    b.Property<string>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Weather");

                    b.HasKey("Id");

                    b.ToTable("SampleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
